resource-pack=https://raw.githubusercontent.com/josephdwebb/MinecraftAero/main/releases/aerie-resources.zip?v=6340f0ac3eb79b6db92f96f6082320c12bad6502
resource-pack-sha1=6340f0ac3eb79b6db92f96f6082320c12bad6502
require-resource-pack=true
resource-pack-prompt={"text": "Install the Outlands of Aerie soundtrack for your arrival."}
