motd=§bLosertown §7— Create + Aeronautics
level-name=world
level-seed=-7833842402223417925
gamemode=survival
difficulty=normal
max-players=8
white-list=true
enforce-whitelist=true
online-mode=true
view-distance=16
simulation-distance=8
allow-flight=true
spawn-protection=0
enable-rcon=true
rcon.port=25575
rcon.password=ilovegian
broadcast-rcon-to-ops=false
sync-chunk-writes=false
max-tick-time=120000
