name = "Aero Server"
author = "josephdwebb/MinecraftAero"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e74027e00e4b7a23e9fcda9f0b76c33bd44fed4c9f99911c9fa912d14b25a6d8"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.250"
