name = "Aero Server"
author = "josephdwebb/MinecraftAero"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bb555805051ce4e6c7218383c154b30588ee4d229d61e8640e4dc8a7a1f9c32b"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.250"
