name = "Aero Server"
author = "josephdwebb/MinecraftAero"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c3fd1b10f6d2674f22910e1d1240c42af5d39d78f4c90df575382e8da5be0179"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.250"
